apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-mysql
  labels:
    app: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
      tier: mysql
  template:
    metadata:
      labels:
        app: wp
        tier: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql

